<a href="https://colab.research.google.com/github/RENISA-GRACELIN/Online_Internship_Projects/blob/main/R_SVM_IV3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import os
import numpy as np
from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.preprocessing import image
import tensorflow as tf
from tensorflow.keras import layers
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix


In [2]:
from google.colab import drive
drive.mount('/content/drive')

# Data directories
train_dir = '/content/drive/MyDrive/DR_50/Train'
test_dir = '/content/drive/MyDrive/DR_50/Test'
valid_dir = '/content/drive/MyDrive/DR_50/Valid'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# Image dimensions
img_width, img_height = 300, 300  # Adjust according to your image dimensions
batch_size = 32
num_epochs = 20

In [4]:
# Load VGG16 model for feature extraction
model = InceptionV3(weights='imagenet', include_top=False)

In [5]:
# Function to extract features from an image
def extract_features(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img_data = image.img_to_array(img)
    img_data = np.expand_dims(img_data, axis=0)
    img_data = preprocess_input(img_data)
    features = model.predict(img_data)
    return features

In [6]:
# Load images and extract features
x_train, y_train = [], []
for i in range(5):
    class_dir = os.path.join(train_dir, str(i))
    for img_path in os.listdir(class_dir):
        features = extract_features(os.path.join(class_dir, img_path))
        x_train.append(features)
        y_train.append(i)


1/1 [==============================] - 0s 189ms/step


In [7]:
# Evaluate on test set
test_dir = '/content/drive/MyDrive/DR_50/Test'
x_test, y_test = [], []
for i in range(5):
    class_dir = os.path.join(test_dir, str(i))
    for img_path in os.listdir(class_dir):
        features = extract_features(os.path.join(class_dir, img_path))
        x_test.append(features)
        y_test.append(i)


1/1 [==============================] - 0s 157ms/step


In [8]:
# Flatten the features
x_train_flat = np.array([feature.flatten() for feature in x_train])
x_test_flat = np.array([feature.flatten() for feature in x_test])

# List of kernels to try
kernels = ['linear', 'poly', 'rbf', 'sigmoid']

for kernel in kernels:
    print(f"Training SVM with {kernel} kernel...")

    # Train SVM classifier
    clf = svm.SVC(kernel=kernel)
    clf.fit(x_train_flat, y_train)

    # Predict on test set
    y_pred = clf.predict(x_test_flat)


    # Predict on test set
    y_pred = clf.predict(x_test_flat)

    # Print performance metrics
    print(f'Performance metrics for {kernel} kernel:')
    print('Classification Report:')
    print(metrics.classification_report(y_test, y_pred))

    # Additional performance metrics
    accuracy = metrics.accuracy_score(y_test, y_pred)
    sensitivity = metrics.recall_score(y_test, y_pred, average='macro')
    precision = metrics.precision_score(y_test, y_pred, average='macro')
    f1 = metrics.f1_score(y_test, y_pred, average='macro')

    print(f'Accuracy: {accuracy}')
    print(f'Sensitivity: {sensitivity}')
    print(f'Precision: {precision}')
    print(f'F1 Score: {f1}\n')


Training SVM with linear kernel...
Performance metrics for linear kernel:
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       1.00      0.60      0.75         5
           2       0.67      0.80      0.73         5
           3       0.75      0.60      0.67         5
           4       0.83      1.00      0.91         5

    accuracy                           0.72        25
   macro avg       0.75      0.72      0.72        25
weighted avg       0.75      0.72      0.72        25

Accuracy: 0.72
Sensitivity: 0.72
Precision: 0.75
F1 Score: 0.7196969696969696

Training SVM with poly kernel...
Performance metrics for poly kernel:
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       1.00      0.60      0.75         5
           2       0.75      0.60      0.67         5
           3       0.50  

In [9]:
# Print performance metrics
print('Classification Report:')
print(classification_report(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.60      0.50         5
           1       0.75      0.60      0.67         5
           2       0.67      0.40      0.50         5
           3       0.60      0.60      0.60         5
           4       0.83      1.00      0.91         5

    accuracy                           0.64        25
   macro avg       0.66      0.64      0.64        25
weighted avg       0.66      0.64      0.64        25

Confusion Matrix:
[[3 0 1 1 0]
 [1 3 0 1 0]
 [2 0 2 0 1]
 [1 1 0 3 0]
 [0 0 0 0 5]]


In [11]:
 # Print performance metrics
print(f'Performance metrics for {kernel} kernel:')
print('Classification Report:')
print(metrics.classification_report(y_test, y_pred))

from sklearn.preprocessing import LabelBinarizer

# Convert y_test and y_pred to binary/multilabel indicator format
lb = LabelBinarizer()
y_test_bin = lb.fit_transform(y_test)
y_pred_bin = lb.transform(y_pred)

# Now you can calculate the AUC
auc = metrics.roc_auc_score(y_test_bin, y_pred_bin,
                            multi_class='ovr')

# Additional performance metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
sensitivity = metrics.recall_score(y_test, y_pred, average='macro')
precision = metrics.precision_score(y_test, y_pred, average='macro')
f1 = metrics.f1_score(y_test, y_pred, average='macro')

print(f'Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Sensitivity: {sensitivity}')
print(f'Precision: {precision}')
print(f'F1 Score: {f1}\n')

Performance metrics for sigmoid kernel:
Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.60      0.50         5
           1       0.75      0.60      0.67         5
           2       0.67      0.40      0.50         5
           3       0.60      0.60      0.60         5
           4       0.83      1.00      0.91         5

    accuracy                           0.64        25
   macro avg       0.66      0.64      0.64        25
weighted avg       0.66      0.64      0.64        25

Accuracy: 0.64
AUC: 0.775
Sensitivity: 0.64
Precision: 0.6557142857142858
F1 Score: 0.6351515151515151

